### ISSUE TITLE
Merging nodes and aliases

### ISSUE THREAD

**Issue by jimmytidey** [jimmytidey/obs#12]
Sometimes two nodes obviously refer to the same thing. It should be possibly to point all references to one of the duplicates to the other, delete the old one, and ensure that in future the duplicate is not recreated. 

This would mean adding some kind of "alias" to the node, so that the alternate version is not readded by the system.

**Comment by richsilv** [comment]
Will be resolved by the concept of linking nodes, rather than with aliases.
