### ISSUE TITLE
Handling URL nodes

### ISSUE THREAD

**Issue by jimmytidey** [jimmytidey/obs#5]
URLS in updates are marked as nodes. It's unclear if the domain, subdomain, or whole URL should be used for this. In the case of Tumblr subdomain seems appropriate, for a link to twitter the whole URL seems appropriate, in case the of other sites the domain seems appropriate.

**Comment by richsilv** [comment]
Include domain, subdomain, entire URL, and then add functionality to ignore nodes which are too generic to provide useful information (e.g. *twitter.com*).
